name: A workfolow for my Hello World file
on: push
jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          INPUT_MY_NAME: "Emma"
